INSERT INTO public.questions
  (game_pack_id, category, round_type, question_type, difficulty, question_text, answer_options, correct_answer, explanation, source, timer_seconds, challenge_format, active)
SELECT
  '74cbc17d-f549-40b7-b29b-a2ae621ad4a8'::uuid,
  v.category,
  'yeah_nah'::round_type,
  'yeah_nah'::question_type,
  v.difficulty,
  v.question_text,
  '[{"key":"yeah","text":"Yeah"},{"key":"nah","text":"Nah"}]'::jsonb,
  jsonb_build_object('key', v.correct_key),
  v.explanation,
  v.source,
  5,
  'yeah_nah',
  true
FROM (VALUES
  ('Geography',1,'Auckland is New Zealand''s capital city.','nah','Wellington has been the capital since 1865 — Auckland is just the biggest city.','DEVELOPMENT/TEST CONTENT — requires final editorial verification'),
  ('Geography',2,'The South Island is larger than the North Island by land area.','yeah','The South Island is roughly a third bigger by area, despite having far fewer people.','DEVELOPMENT/TEST CONTENT — requires final editorial verification'),
  ('Geography',2,'Aoraki / Mount Cook is the highest mountain in New Zealand.','yeah','It tops out around 3,724 metres.','DEVELOPMENT/TEST CONTENT — requires final editorial verification'),
  ('Geography',3,'The Clutha is New Zealand''s longest river.','nah','The Waikato is the longest; the Clutha carries the most water.','DEVELOPMENT/TEST CONTENT — requires final editorial verification'),
  ('Geography',1,'New Zealand shares a land border with Australia.','nah','About 2,000 km of Tasman Sea says otherwise.','DEVELOPMENT/TEST CONTENT — requires final editorial verification'),
  ('Geography',2,'Milford Sound is technically a fiord, not a sound.','yeah','It was carved by glaciers, which makes it a fiord — hence Fiordland.','DEVELOPMENT/TEST CONTENT — requires final editorial verification'),
  ('Geography',2,'Lake Taupō sits inside a volcanic caldera.','yeah','It fills the caldera left by one of the largest eruptions of the last 5,000 years.','DEVELOPMENT/TEST CONTENT — requires final editorial verification'),
  ('Geography',1,'Mount Taranaki is in the South Island.','nah','Taranaki stands on the west coast of the North Island.','DEVELOPMENT/TEST CONTENT — requires final editorial verification'),
  ('Geography',2,'Wellington is the largest city in New Zealand by population.','nah','Auckland is comfortably the largest.','DEVELOPMENT/TEST CONTENT — requires final editorial verification'),
  ('Places',2,'Rotorua is known for geothermal activity and a sulphur smell.','yeah','Geysers, mud pools and that unmistakable whiff.','DEVELOPMENT/TEST CONTENT — requires final editorial verification'),
  ('Places',2,'Bluff is famous for its oysters.','yeah','Bluff oysters get their own season and their own festival.','DEVELOPMENT/TEST CONTENT — requires final editorial verification'),
  ('Places',3,'Stewart Island''s Māori name is Rakiura.','yeah','Rakiura is often translated as "glowing skies".','DEVELOPMENT/TEST CONTENT — HUMAN VERIFICATION REQUIRED (te reo Māori)'),
  ('Places',2,'Te Papa, the national museum, is in Christchurch.','nah','Te Papa is on the Wellington waterfront.','DEVELOPMENT/TEST CONTENT — requires final editorial verification'),
  ('Wildlife',2,'The kea is the world''s only alpine parrot.','yeah','It lives in the Southern Alps and is famous for wrecking car aerials.','DEVELOPMENT/TEST CONTENT — requires final editorial verification'),
  ('Wildlife',1,'There are no native land snakes in New Zealand.','yeah','No native land snakes at all — just sea snakes that drift in occasionally.','DEVELOPMENT/TEST CONTENT — requires final editorial verification'),
  ('Wildlife',2,'The kākāpō is a flightless, nocturnal parrot.','yeah','It''s the world''s heaviest parrot and can''t fly.','DEVELOPMENT/TEST CONTENT — requires final editorial verification'),
  ('Wildlife',3,'The tuatara is a lizard.','nah','Tuatara are the last survivors of their own reptile order, not lizards.','DEVELOPMENT/TEST CONTENT — requires final editorial verification'),
  ('Wildlife',3,'Kiwi lay one of the smallest eggs relative to body size of any bird.','nah','It''s the opposite — kiwi eggs are enormous relative to the bird.','DEVELOPMENT/TEST CONTENT — requires final editorial verification'),
  ('Wildlife',1,'Moa still survive in remote parts of Fiordland.','nah','Moa have been extinct for centuries, sorry.','DEVELOPMENT/TEST CONTENT — requires final editorial verification'),
  ('Nature',2,'The pōhutukawa is often called New Zealand''s Christmas tree.','yeah','It flowers bright red around December.','DEVELOPMENT/TEST CONTENT — requires final editorial verification'),
  ('Food',1,'Hokey pokey ice cream contains pieces of honeycomb toffee.','yeah','Vanilla ice cream studded with hokey pokey toffee.','DEVELOPMENT/TEST CONTENT — requires final editorial verification'),
  ('Food',1,'Pineapple Lumps are chewy pineapple-flavoured lollies covered in chocolate.','yeah','A Kiwi dairy classic.','DEVELOPMENT/TEST CONTENT — requires final editorial verification'),
  ('Food',2,'Marmite and Vegemite are the same product sold under two names.','nah','Different recipes, different companies, and Kiwis will argue about it.','DEVELOPMENT/TEST CONTENT — requires final editorial verification'),
  ('Food',2,'Kiwifruit originally came from China.','yeah','It was grown in China long before New Zealand renamed and exported it.','DEVELOPMENT/TEST CONTENT — requires final editorial verification'),
  ('Food',3,'A hāngī is cooked in an above-ground clay oven.','nah','A hāngī is cooked in an earth oven, using heated stones in a pit.','DEVELOPMENT/TEST CONTENT — HUMAN VERIFICATION REQUIRED (tikanga)'),
  ('Slang',1,'"Chur" is a Kiwi way of saying thanks or sweet as.','yeah','Chur, bro.','DEVELOPMENT/TEST CONTENT — requires final editorial verification'),
  ('Slang',1,'In New Zealand, a "dairy" means a corner shop.','yeah','Nothing to do with milking sheds.','DEVELOPMENT/TEST CONTENT — requires final editorial verification'),
  ('Slang',1,'"Jandals" is the Kiwi word for gumboots.','nah','Jandals are flip flops. Gumboots are gumboots.','DEVELOPMENT/TEST CONTENT — requires final editorial verification'),
  ('History',2,'New Zealand was the first self-governing country to give women the vote in national elections.','yeah','Women won the vote in 1893.','DEVELOPMENT/TEST CONTENT — HUMAN VERIFICATION REQUIRED (historical claim)'),
  ('Culture',2,'Te reo Māori is an official language of New Zealand.','yeah','It was made an official language by the Māori Language Act 1987.','DEVELOPMENT/TEST CONTENT — HUMAN VERIFICATION REQUIRED (legal/te reo Māori claim)'),
  ('TV',1,'Shortland Street is a long-running New Zealand soap opera.','yeah','On air since 1992.','DEVELOPMENT/TEST CONTENT — requires final editorial verification'),
  ('Music',3,'Split Enz and Crowded House both featured Neil Finn.','yeah','Neil Finn played in both bands.','DEVELOPMENT/TEST CONTENT — requires final editorial verification'),
  ('Symbols',2,'The current New Zealand flag features a silver fern.','nah','The flag has the Union Jack and four red stars — the fern lost the 2016 referendum.','DEVELOPMENT/TEST CONTENT — requires final editorial verification'),
  ('Symbols',3,'The bird on the New Zealand one dollar coin is a tūī.','nah','It''s a kiwi.','DEVELOPMENT/TEST CONTENT — requires final editorial verification'),
  ('Everyday',1,'New Zealand uses the Australian dollar as its currency.','nah','New Zealand has its own dollar.','DEVELOPMENT/TEST CONTENT — requires final editorial verification'),
  ('Sport',2,'Rugby league is officially New Zealand''s national sport, ahead of rugby union.','nah','New Zealand has no legally designated national sport, and union is the widely recognised one.','DEVELOPMENT/TEST CONTENT — HUMAN VERIFICATION REQUIRED (national-symbol claim)')
) AS v(category, difficulty, question_text, correct_key, explanation, source);