WITH pack AS (SELECT id FROM public.game_packs WHERE slug = 'kiwi-as-quickie' LIMIT 1)
INSERT INTO public.questions
  (game_pack_id, category, round_type, question_type, challenge_format, difficulty, question_text, answer_options, correct_answer, explanation, timer_seconds, active, source)
SELECT pack.id, v.category, 'showdown'::round_type, v.qtype::question_type, v.fmt, v.difficulty, v.qtext, v.opts::jsonb, v.ans::jsonb, v.expl, 10, true, 'dev-content'
FROM pack, (VALUES
 ('Geography','multiple_choice','single_choice',2,'Which is New Zealand''s highest mountain?','[{"key":"a","text":"Aoraki / Mount Cook"},{"key":"b","text":"Mount Taranaki"},{"key":"c","text":"Mount Ruapehu"},{"key":"d","text":"Mount Aspiring"}]','{"key":"a"}','Aoraki / Mount Cook tops out at about 3,724 metres.'),
 ('Places','multiple_choice','single_choice',1,'Which city is known as the City of Sails?','[{"key":"a","text":"Auckland"},{"key":"b","text":"Wellington"},{"key":"c","text":"Tauranga"},{"key":"d","text":"Napier"}]','{"key":"a"}','Auckland has one of the highest boats-per-person rates in the world.'),
 ('History','multiple_choice','single_choice',3,'Who was New Zealand''s first woman Prime Minister?','[{"key":"a","text":"Jenny Shipley"},{"key":"b","text":"Helen Clark"},{"key":"c","text":"Jacinda Ardern"},{"key":"d","text":"Dame Whina Cooper"}]','{"key":"a"}','Jenny Shipley took office in 1997.'),
 ('History','multiple_choice','single_choice',2,'In what year did New Zealand women win the right to vote?','[{"key":"a","text":"1893"},{"key":"b","text":"1883"},{"key":"c","text":"1901"},{"key":"d","text":"1919"}]','{"key":"a"}','A world first in 1893.'),
 ('Geography','multiple_choice','single_choice',2,'Which is New Zealand''s longest river?','[{"key":"a","text":"Waikato"},{"key":"b","text":"Clutha"},{"key":"c","text":"Whanganui"},{"key":"d","text":"Rangitīkei"}]','{"key":"a"}','The Waikato runs about 425 km.'),
 ('Te Reo','multiple_choice','single_choice',2,'Which name refers to the South Island?','[{"key":"a","text":"Te Waipounamu"},{"key":"b","text":"Te Ika-a-Māui"},{"key":"c","text":"Rakiura"},{"key":"d","text":"Aotea"}]','{"key":"a"}','Te Ika-a-Māui is the North Island; Rakiura is Stewart Island.'),
 ('Science','multiple_choice','single_choice',3,'Which New Zealand-born physicist first split the atom?','[{"key":"a","text":"Ernest Rutherford"},{"key":"b","text":"William Pickering"},{"key":"c","text":"Maurice Wilkins"},{"key":"d","text":"Beatrice Tinsley"}]','{"key":"a"}','Rutherford, from Brightwater, is the father of nuclear physics.'),
 ('Nature','multiple_choice','single_choice',2,'Tāne Mahuta, the giant of Waipoua Forest, is which kind of tree?','[{"key":"a","text":"Kauri"},{"key":"b","text":"Tōtara"},{"key":"c","text":"Rimu"},{"key":"d","text":"Pōhutukawa"}]','{"key":"a"}','Tāne Mahuta is the largest known living kauri.'),
 ('Geography','multiple_choice','single_choice',3,'Which is New Zealand''s deepest lake?','[{"key":"a","text":"Lake Hauroko"},{"key":"b","text":"Lake Taupō"},{"key":"c","text":"Lake Wakatipu"},{"key":"d","text":"Lake Te Anau"}]','{"key":"a"}','Hauroko in Fiordland reaches about 462 metres.'),
 ('Nature','multiple_choice','single_choice',2,'Which native bird is the world''s heaviest parrot?','[{"key":"a","text":"Kākāpō"},{"key":"b","text":"Kea"},{"key":"c","text":"Kākā"},{"key":"d","text":"Weka"}]','{"key":"a"}','The flightless kākāpō can top 3 kg. (The weka isn''t a parrot at all.)'),
 ('Places','multiple_choice','which_one_is_real',2,'Which one is a real New Zealand town?','[{"key":"a","text":"Tinwald"},{"key":"b","text":"Bramblewick"},{"key":"c","text":"Fernhollow"},{"key":"d","text":"Kōwhaiton"}]','{"key":"a"}','Tinwald sits just south of Ashburton.'),
 ('Nature','multiple_choice','which_one_is_real',3,'Which one is a real native New Zealand bird?','[{"key":"a","text":"Whio"},{"key":"b","text":"Kārere"},{"key":"c","text":"Tuiwhē"},{"key":"d","text":"Piriroa"}]','{"key":"a"}','The whio is the blue duck on the $10 note.'),
 ('Kai','multiple_choice','which_one_is_real',1,'Which one is a real Kiwi chocolate bar?','[{"key":"a","text":"Perky Nana"},{"key":"b","text":"Chunky Kiwi"},{"key":"c","text":"Hokey Bomb"},{"key":"d","text":"Buzzy Crunch"}]','{"key":"a"}','Perky Nana: banana fudge, chocolate coating.'),
 ('Geography','multiple_choice','which_one_is_real',3,'Which one is a real New Zealand mountain range?','[{"key":"a","text":"Kaimanawa Range"},{"key":"b","text":"Waimangu Spurs"},{"key":"c","text":"Tarahiko Range"},{"key":"d","text":"Puketoa Ridges"}]','{"key":"a"}','The Kaimanawa Range sits in the central North Island.'),
 ('Geography','multiple_choice','which_one_is_real',2,'Which one is a real New Zealand lake?','[{"key":"a","text":"Lake Rotoiti"},{"key":"b","text":"Lake Manawhenua"},{"key":"c","text":"Lake Tarakina"},{"key":"d","text":"Lake Ohinemoa"}]','{"key":"a"}','There are Lake Rotoitis in both Nelson Lakes and Rotorua.'),
 ('History','two_choice','which_came_first',2,'Which came first?','[{"key":"a","text":"Edmund Hillary summits Everest","detail":"1953"},{"key":"b","text":"New Zealand''s first television broadcast","detail":"1960"}]','{"key":"a"}','Everest in 1953; television arrived in 1960.'),
 ('History','two_choice','which_came_first',1,'Which came first?','[{"key":"a","text":"The Treaty of Waitangi is signed","detail":"1840"},{"key":"b","text":"The Otago gold rush begins","detail":"1861"}]','{"key":"a"}','Waitangi 1840, Gabriel''s Gully 1861.'),
 ('History','two_choice','which_came_first',3,'Which came first?','[{"key":"a","text":"The Rainbow Warrior bombing","detail":"1985"},{"key":"b","text":"New Zealand''s nuclear-free law","detail":"1987"}]','{"key":"a"}','The bombing in 1985 preceded the 1987 legislation.'),
 ('History','two_choice','which_came_first',2,'Which came first?','[{"key":"a","text":"The All Blacks win the first Rugby World Cup","detail":"1987"},{"key":"b","text":"New Zealand''s first MMP election","detail":"1996"}]','{"key":"a"}','1987 at Eden Park; MMP arrived in 1996.'),
 ('Nature','multiple_choice','doesnt_belong',1,'Which one doesn''t belong?','[{"key":"a","text":"Possum"},{"key":"b","text":"Kea"},{"key":"c","text":"Kākāpō"},{"key":"d","text":"Tūī"}]','{"key":"a"}','The others are native birds; the possum is an introduced pest.'),
 ('Places','multiple_choice','doesnt_belong',1,'Which one doesn''t belong?','[{"key":"a","text":"Suva"},{"key":"b","text":"Auckland"},{"key":"c","text":"Wellington"},{"key":"d","text":"Christchurch"}]','{"key":"a"}','Suva is the capital of Fiji.'),
 ('Kai','multiple_choice','doesnt_belong',3,'Which one doesn''t belong?','[{"key":"a","text":"Barossa"},{"key":"b","text":"Marlborough"},{"key":"c","text":"Hawke''s Bay"},{"key":"d","text":"Central Otago"}]','{"key":"a"}','Barossa is an Australian wine region.'),
 ('Culture','yeah_nah','yeah_nah',1,'New Zealand has more sheep than people.','[{"key":"yeah","text":"Yeah"},{"key":"nah","text":"Nah"}]','{"key":"yeah"}','Roughly five sheep for every person.'),
 ('Places','yeah_nah','yeah_nah',2,'Wellington is the world''s southernmost capital city.','[{"key":"yeah","text":"Yeah"},{"key":"nah","text":"Nah"}]','{"key":"yeah"}','Southernmost capital of a sovereign state.'),
 ('Nature','yeah_nah','yeah_nah',1,'The kiwi can fly short distances.','[{"key":"yeah","text":"Yeah"},{"key":"nah","text":"Nah"}]','{"key":"nah"}','Kiwi are completely flightless.')
) AS v(category, qtype, fmt, difficulty, qtext, opts, ans, expl);