INSERT INTO public.questions (game_pack_id, category, round_type, question_type, difficulty, question_text, answer_options, correct_answer, explanation, timer_seconds, active)
SELECT p.id, q.category, 'sweet_as'::round_type, 'multiple_choice'::question_type, 1, q.question_text, q.answer_options, q.correct_answer, q.explanation, 12, true
FROM public.game_packs p,
(VALUES
 ('Places', 'Which town is famous for its giant carrot?', '[{"key":"a","text":"Gore"},{"key":"b","text":"Ohakune"},{"key":"c","text":"Cambridge"},{"key":"d","text":"Geraldine"}]'::jsonb, '{"key":"b"}'::jsonb, 'Home of the famous giant carrot.'),
 ('Places', 'Which city is known as the Garden City?', '[{"key":"a","text":"Auckland"},{"key":"b","text":"Christchurch"},{"key":"c","text":"Hamilton"},{"key":"d","text":"Dunedin"}]'::jsonb, '{"key":"b"}'::jsonb, 'Christchurch earned the name from its parks and gardens.'),
 ('Icons', 'Which bird appears on New Zealand''s $1 coin?', '[{"key":"a","text":"Tui"},{"key":"b","text":"Kiwi"},{"key":"c","text":"Kea"},{"key":"d","text":"Kereru"}]'::jsonb, '{"key":"b"}'::jsonb, 'The kiwi has been on the dollar coin since 1991.'),
 ('Kai', 'L&P originally comes from which New Zealand town?', '[{"key":"a","text":"Paeroa"},{"key":"b","text":"Rotorua"},{"key":"c","text":"Nelson"},{"key":"d","text":"Napier"}]'::jsonb, '{"key":"a"}'::jsonb, 'Lemon & Paeroa — world famous in New Zealand.'),
 ('Music', 'Which group released "How Bizarre"?', '[{"key":"a","text":"Supergroove"},{"key":"b","text":"OMC"},{"key":"c","text":"SIX60"},{"key":"d","text":"Dragon"}]'::jsonb, '{"key":"b"}'::jsonb, 'OMC took How Bizarre around the world in 1995.'),
 ('Places', 'What is the capital city of New Zealand?', '[{"key":"a","text":"Auckland"},{"key":"b","text":"Wellington"},{"key":"c","text":"Christchurch"},{"key":"d","text":"Hamilton"}]'::jsonb, '{"key":"b"}'::jsonb, 'Wellington became the capital in 1865.'),
 ('Nature', 'What is New Zealand''s highest mountain?', '[{"key":"a","text":"Mount Taranaki"},{"key":"b","text":"Mount Ruapehu"},{"key":"c","text":"Aoraki / Mount Cook"},{"key":"d","text":"Mount Aspiring"}]'::jsonb, '{"key":"c"}'::jsonb, 'Aoraki / Mount Cook stands about 3,724 metres.'),
 ('Sport', 'What is the name of the national rugby union team?', '[{"key":"a","text":"All Blacks"},{"key":"b","text":"Black Caps"},{"key":"c","text":"Silver Ferns"},{"key":"d","text":"Tall Blacks"}]'::jsonb, '{"key":"a"}'::jsonb, 'The Black Caps play cricket, the Silver Ferns netball.'),
 ('People', 'Who was the first woman to be elected Prime Minister of New Zealand?', '[{"key":"a","text":"Helen Clark"},{"key":"b","text":"Jenny Shipley"},{"key":"c","text":"Jacinda Ardern"},{"key":"d","text":"Dame Whina Cooper"}]'::jsonb, '{"key":"a"}'::jsonb, 'Jenny Shipley was first to hold the office, but Helen Clark was the first elected to it in 1999.'),
 ('Nature', 'Which lake is New Zealand''s largest by surface area?', '[{"key":"a","text":"Lake Wakatipu"},{"key":"b","text":"Lake Te Anau"},{"key":"c","text":"Lake Taupo"},{"key":"d","text":"Lake Wanaka"}]'::jsonb, '{"key":"c"}'::jsonb, 'Lake Taupo sits in a huge volcanic caldera.'),
 ('Places', 'Which city is nicknamed the City of Sails?', '[{"key":"a","text":"Auckland"},{"key":"b","text":"Tauranga"},{"key":"c","text":"Napier"},{"key":"d","text":"Nelson"}]'::jsonb, '{"key":"a"}'::jsonb, 'Auckland has more boats per capita than most places on earth.'),
 ('Kai', 'A "chilly bin" is what in the rest of the world?', '[{"key":"a","text":"A rubbish bin"},{"key":"b","text":"A cooler"},{"key":"c","text":"A freezer"},{"key":"d","text":"A lunchbox"}]'::jsonb, '{"key":"b"}'::jsonb, 'Kiwi for a portable cooler box.')
) AS q(category, question_text, answer_options, correct_answer, explanation)
WHERE p.slug = 'kiwi-as-quickie';